language: node_js
node_js: 
    - '11'
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "HaiRongHaHA"
  - git config user.email "whr9743@163.com"
  - git add -A
  - git commit -m "Update documents"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" "main:gh-pages"
branches:
  only:
    - main
